import type { AccessControlRoleRecord } from '@/application/vault/useAccessControlData';

export default function RolesList({ roles }: { readonly roles: readonly AccessControlRoleRecord[] }) {
  return (
    <section aria-labelledby="roles-heading" className="min-h-0 flex-1 overflow-y-auto">
      <header className="border-b border-background-200 px-5 py-3"><p className="font-mono text-[9px] font-semibold uppercase tracking-[0.16em] text-primary-600">Managed ACL policies</p><div className="flex items-center gap-2"><h1 id="roles-heading" className="text-sm font-semibold text-foreground-900">Roles</h1><span className="text-xs text-foreground-400">{roles.length}</span></div></header>
      <div className="p-3 sm:p-5"><div className="overflow-x-auto rounded-lg border border-background-300"><table className="w-full min-w-[640px]"><thead><tr className="border-b border-background-200 bg-background-100"><th className="px-4 py-2.5 text-left text-[11px] font-medium text-foreground-500">Role</th><th className="px-4 py-2.5 text-left text-[11px] font-medium text-foreground-500">Policy</th><th className="px-4 py-2.5 text-left text-[11px] font-medium text-foreground-500">Parsed paths</th><th className="px-4 py-2.5 text-left text-[11px] font-medium text-foreground-500">State</th></tr></thead><tbody>{roles.map((role) => <tr key={role.id} className="border-b border-background-100"><td className="px-4 py-3 text-sm font-medium text-foreground-800">{role.name}</td><td className="px-4 py-3 font-mono text-xs text-foreground-600">{role.policyName}</td><td className="px-4 py-3 font-mono text-xs text-foreground-500">{role.rules?.length ?? '—'}</td><td className="px-4 py-3"><span className={`rounded px-1.5 py-0.5 text-[10px] font-medium ${role.rules ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{role.rules ? 'Visual' : 'HCL only'}</span></td></tr>)}</tbody></table>{roles.length === 0 && <div className="py-16 text-center text-sm text-foreground-500">No policies with the <span className="font-mono">vc-role-</span> prefix.</div>}</div></div>
    </section>
  );
}
